### ISSUE TITLE
[ISSUE] Navigation of the header

### ISSUE THREAD

**Issue by Abhijeet-Anand-01** [hackclubiter/projects#7]
Hello there,
In the header section (navbar), Navigation from Project page to About, Team, and Contact is not working.

I can resolve this issue for you.
You can assign it to me.
Thank you :)

**Comment by saswatsamal** [comment]
Assigned

**Comment by Abhijeet-Anand-01** [comment]
I have generated the PR.
Please have a look on it.
If any modifications required then please let me know.
Thanks :)
